### PR TITLE
Fil r.coppelia sim interface

### PR DESCRIPTION
**Pull request by studywolf**
Moves from VREP to CoppeliaSim, the new version.

- all examples updated
- also fixes a small typo in the README

### CODE REVIEW

**Comment by studywolf** [comment]
@filRocha can you please sign the CAA to get your permission to merge this into ABR Control?

**Comment by studywolf** [comment]
@p3jawors can you update the graphic in the README to say CoppeliaSim instead of VREP?

**Comment by studywolf** [comment]
@filRocha sorry i meant to link the CAA, it's here: https://www.nengo.ai/caa/

please confirm when it's signed

**Comment by studywolf** [comment]
Updated the README text also, so as soon as @filRocha signs the CAA we're good to merge this

**Comment by filRocha** [comment]
> Updated the README text also, so as soon as @filRocha signs the CAA we're good to merge this

I am sorry for my ignorance, but how exactly do I perform this?

**Comment by studywolf** [comment]
No problem! So at this site https://www.nengo.ai/caa/ there is the disclaimer that you need to read, and once you've read that if you can make a PR to the nengo.github.io repo with your name added to the https://github.com/nengo/nengo.github.io/blob/master/people.md file then we'll be all set!

**Comment by filRocha** [comment]
> No problem! So at this site https://www.nengo.ai/caa/ there is the disclaimer that you need to read, and once you've read that if you can make a PR to the nengo.github.io repo with your name added to the https://github.com/nengo/nengo.github.io/blob/master/people.md file then we'll be all set!

Done! :dancer:

**Comment by studywolf** [comment]
great, merged! Thanks for the PR @filRocha!

**Pull request merged**
