### PR TITLE
Moved scaling function from abr_analyze

### PR DESCRIPTION
**Pull request by p3jawors**
- function for scaling inputs for spherical conversion using the nengolib
function moved from abr_analyze.network_utils to dynamics_adaptation
- moved test for this function as well to avoid rewriting it

### CODE REVIEW

**Comment by studywolf** [comment]
what is the use case for `in_index`?

**Comment by studywolf** [comment]
i think a bunch of work still needs to be done on this PR. there's the `scaleup` and `scaledown` functions in `base_config.py`, which do the same thing. Probably just moving them to the DynamicsAdaptation class and having MEANS and SCALES be passed in to that when it's created is the way to go.

**Comment by studywolf** [comment]
i can make these changes but i'll wait for discussion before moving ahead, i assume i'm missing out on some use cases

**Comment by p3jawors** [comment]
- rebased to config_debug_features, will check again after it has been merged to master
- travis ci checks pass

- removed scaledown and scaleup from arm config and config test
- renamed SCALES to VARIANCES
- dynamics adaptation accepts MEANS, VARIANCES, and spherical in __init__
- MEANS and VARIANCES are no longer dicts, the user has to align dimensions with the input_signal being passed in
- generate accepts non-scaled input_signal, scaling is done in generate if MEANS and VARIANCES are not None
- updated examples

**Comment by studywolf** [comment]
can you rebase this one before i look it over?

**Comment by studywolf** [comment]
there are changes in the path planners etc, which i think shouldn't be?

**Comment by studywolf** [comment]
#46 fixed the rebase issues and has been merged

**Pull request closed without merging**
